### ISSUE TITLE
How to define config settings?

### ISSUE THREAD

**Issue by it-can** [elibyy/tcpdf-laravel#10]
Is there an easy way to define a couple of of constants from the tcpdf_config?

Now I have to do this on every function that I use tcpdf

```
define('K_THAI_TOPCHARS', false);
```

Is there a way to do this globally? I tried adding it to the tcpdf.php config file in Laravel, but then the tests fail...

**Comment by elibyy** [comment]
so with the pull request, this can be closed?

**Comment by it-can** [comment]
yes
