### ISSUE TITLE
Installation problem at Laravel 7

### ISSUE THREAD

**Issue by nusagates** [elibyy/tcpdf-laravel#100]
is this repo not supported to Laravel 7?

Today i installed this repo on my project using Laravel 7 but i cannot.
I got this error:
`  - elibyy/tcpdf-laravel 6.0.2 requires illuminate/support ^6.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2
, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11,
 v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6
.18.27, v6.18.28, v6.18.29, v6.18.3, v6.18.30, v6.18.31, v6.18.32, v6.18.33, v6.18.34, v6.18.35, v6.18.36, v6.18.37, v6.18.38, v6.18.39, v6.18.4, v6.18.40, v6.18.
5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
`

Full error log are enclosed: [error.txt](https://github.com/elibyy/tcpdf-laravel/files/5296026/error.txt)

**Comment by elibyy** [comment]
You should use version [7.0.0](https://packagist.org/packages/elibyy/tcpdf-laravel#7.0.0)
