### ISSUE TITLE
Support for TCPDF_PARSER

### ISSUE THREAD

**Issue by sotoh** [elibyy/tcpdf-laravel#104]
Your library is currently working with TCPDF class. Any plans to use the parser?
The above is to avoid using multiple libraries and work in this one.
Greetings.

**Comment by elibyy** [comment]
Hey there, I'm not really sure what that means?
Could you please elaborate or provide some samples of the usage for this parser?
Thanks

**Comment by sotoh** [comment]
TCPDF library has various classes, and TCPDF_PARSER is one fo them located in "tcpdf_parser.php", your helpers only work with the class TCPDF located in "tcpdf.php".

**Comment by elibyy** [comment]
a. You can use TCPDF_PARSER, it should be included in the library
b. Do you mean that I should add a facade for the parser?

**Comment by sotoh** [comment]
What I was aiming was for the b option, but there I think a issue could arise due to the constructor.  PDF::__constructor? In the end I used the simple inheritance and use the class included (Because at the begining I didn't know how), thanks for the replies anyways .
