### ISSUE TITLE
Error con Php8

### ISSUE THREAD

**Issue by caseroft** [elibyy/tcpdf-laravel#106]
php artisan ide-helper:generate -H
          Exception: Required parameter $currentfont follows optional parameter $isunicode
          Skipping \Elibyy\TCPDF\Facades\TCPDF.
          Exception: Required parameter $tagvspaces follows optional parameter $default_css
          Skipping \Elibyy\TCPDF\Facades\TCPDF.

**Comment by elibyy** [comment]
Hey there,
This is a problem with TCPDF library and not my module.
As far as I know TCPDF isn't supported in PHP 7 even so obviously not on 8

Sorry about that

**Comment by caseroft** [comment]
Gracias, levanto un ticket en TCPDF
