### ISSUE TITLE
laravel 8 error with TCPDF

### ISSUE THREAD

**Issue by jonathanboreljaquet** [elibyy/tcpdf-laravel#108]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v8.12.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.12.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.12.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.12.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.13.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.14.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.15.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.16.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.16.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.17.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.17.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.17.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.18.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.18.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.19.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.20.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.20.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.21.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.22.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.22.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.23.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.23.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.24.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.25.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.26.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.26.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.27.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.28.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v8.28.1 (conflict analysis result)
    - elibyy/tcpdf-laravel 5.5.5 requires illuminate/support 5.6.* -> satisfiable by illuminate/support[v5.6.0, ..., 5.6.x-dev].
    - elibyy/tcpdf-laravel[5.5.0, ..., 5.5.x-dev] require illuminate/support 5.5.* -> satisfiable by illuminate/support[v5.5.0, ..., 5.5.x-dev].
    - Only one of these can be installed: illuminate/support[dev-master, v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev], laravel/framework[v8.12.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^8.12 -> satisfiable by laravel/framework[v8.12.0, ..., 8.x-dev].
    - Root composer.json requires elibyy/tcpdf-laravel 5.5.* -> satisfiable by elibyy/tcpdf-laravel[5.5.0, ..., 5.5.x-dev].

**Comment by it-can** [comment]
It seems you tried to install an older version of the library...

Try to do this:

```
composer require elibyy/tcpdf-laravel
```
