### ISSUE TITLE
Breaking the PDF Generation flow

### ISSUE THREAD

**Issue by salvobee** [elibyy/tcpdf-laravel#112]
I'm using this library like the documentation suggests, always recalling PDF facade to set up meta data, draw elements, writing text blocks, etc.
But what if I don't want to run all the operations in this kind of "procedural style" flavour?

I've to create very complex graphic layouts filled with many data, so I'd like to be able to instantiate an object of my "work in progress" PDF and pass it across several classes / methods to do data manipulations and makes choices upon some logic.

Will be cool if I can break the "pdf generation flow" at some point just to pass an instanciated object to some other action classes and manipulate it with some sort of more fluent syntax.

Is there any way of doing so?

**Comment by elibyy** [comment]
Hey there
In the underlying api we hold a pdf instance which means that each call is on the same instance unless you invoke `PDF::reset`
If you could add more detail to any problem you encounter with this flow I'll try to help
Also, if you want a simple instance you could always instantiate TCPDF directly

**Comment by salvobee** [comment]
Hi, thanks for your reply.
> In the underlying api we hold a pdf instance which means that each call is on the same instance unless you invoke `PDF::reset`

Yes, I had misunderstood the purpose of the package, it's just a facade to TCPDF

> Also, if you want a simple instance you could always instantiate TCPDF directly
Yes, that was what I've did to obtain what I need...

I believe that I'll update my dependencies to include tecnickcom/tcpdf  directly.

Thanks again
