### ISSUE TITLE
The library is not working  

### ISSUE THREAD

**Issue by 1abdullah-saad1** [elibyy/tcpdf-laravel#115]
hey Elibyy I am using your libraryover linux ubuntu it is not working and laravel doesn`t throw any error
in chrom the console is throwing the folowing error

VM6688:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at index.js:58

**Comment by elibyy** [comment]
Hey there,
It seems that you included the AJAX error, this library is server side and not JS
So, if I can help you with any server errors, please provide any laravel logs or PHP errors

--
Eli

**Comment by 1abdullah-saad1** [comment]
this error occurs only when i run this instruction 
PDF::Output('Form1.pdf', 'D')
and I am using livewire to get the response 
thaks alot

**Comment by 1abdullah-saad1** [comment]
the npm consider that there is an error in files starts with (VM) my partner run the same code on (server) windows 10 with no problems but in linux ubuntu 20lts I got this issue 
I think that there is an encoding problem because the VM generated file contian the major objects of pdf but with rubush

**Comment by 1abdullah-saad1** [comment]
![Uploading Screenshot from 2021-06-02 17-20-36.png…]()

**Comment by elibyy** [comment]
Hey there,
So first of all. It seems that the screenshot has failed uploading.
 Secondly, I'm not sure how any of the information helps me, I need to know what error you have received from the server, this library doesn't have anything to do with Javascript and any Javascript info is unrelated.
So please provide any PHP error and I'll be able to try and help
