### ISSUE TITLE
How to adds static typing?

### ISSUE THREAD

**Issue by crescent1** [elibyy/tcpdf-laravel#118]
hi, how to add static typing using this package?
I tried like this, but it doesn't work.

`use Elibyy\TCPDF\Facades\TCPDF as PDF` or `use PDF`

and still giving error message.
example:

`Call to an undefined static method Elibyy\TCPDF\Facades\TCPDF::SetAutoPageBreak().`

the package runs normally but the error message is a little annoying.

**Comment by elibyy** [comment]
Hey there,
sorry for the delay in the response
Are you using auto discovery or have added the provider to the app config?

**Comment by crescent1** [comment]
Hi,
I have added the provider to the app configuration.

`Elibyy\TCPDF\ServiceProvider::class,`

but i also using this package

`nunomaduro/larastan`
