### ISSUE TITLE
Overlapping text when previous page was auto-broke

### ISSUE THREAD

**Issue by Marchiuzzz** [elibyy/tcpdf-laravel#122]
I'm testing this out with longer texts and I'm facing a weird issue with content overlapping. It seems that cursor is not reset to the new page, so I tried `PDF::lastPage();` but that just gives me another error - `Wrong page number on setPage() function: 0`
Here's my problem
Page 1, which breaks to page 2
![image](https://user-images.githubusercontent.com/73941456/146934502-c59db40f-893f-4db3-8398-ca58cae604c4.png)

Page 2:
![image](https://user-images.githubusercontent.com/73941456/146934607-d43a734c-61a1-46e5-b168-29719ab16e68.png)

**Comment by elibyy** [comment]
Hey @Marchiuzzz,
This seems more of TCPDF issue rather than my library which only provides wrapper for it in laravel
you should try and ask [there](https://github.com/tecnickcom/TCPDF)

**Comment by Marchiuzzz** [comment]
Thanks, thought you might have insight what might be wrong. Well I managed to get it working somehow, can't really say what the problem was, I was just tweaking stuff around and it suddenly worked. Thanks for help anyway!

**Comment by eli-amazing** [comment]
Ah, sorry. I'm not that familiar with Tcpdf.
Glad you've found a workaround
