### ISSUE TITLE
How to change tcpdf encoding?

### ISSUE THREAD

**Issue by Marchiuzzz** [elibyy/tcpdf-laravel#123]
Hi, I know about config/tcpdf.php but I also know that changing anything in vendor folder is pointless because it will get overwritten, is there any other way to change these two parameters? Maybe I can publish this config somehow?
![image](https://user-images.githubusercontent.com/73941456/151545798-57219bb1-216a-4aac-8f20-c39499e43858.png)

**Comment by elibyy** [comment]
Of course you can, you can read more in the readme [here](https://github.com/elibyy/tcpdf-laravel#configuration)

**Comment by Marchiuzzz** [comment]
Oh this is embarrassing....how did I miss this in the readme 😄 Thanks!
