### ISSUE TITLE
I am unable show  image through PDF::Image in laravel  project using  tcpdf

### ISSUE THREAD

**Issue by Shubham9527** [elibyy/tcpdf-laravel#126]
I have to project in one project it works fine to show image but it's not working in another project while location and path are same as I have tried the same image at a same and different location it shows in the first project so I have copied the path and syntax and paste it in another project but it didn't work.

Please Help
Thanks.

**Comment by elibyy** [comment]
Hey there,
It would be helpful if you provided a snippet of your code

--
Eli

**Comment by Shubham9527** [comment]
Now It  works It may fault in  my path of image
By the way thanks for creating this amazing library...

**Comment by parimal20** [comment]
To add an image to PDF file use,

public_path('write location inside of public folder here')
