### ISSUE TITLE
the method serializeTCPDFtagParameters does not exists in TCPDF

### ISSUE THREAD

**Issue by susanne99** [elibyy/tcpdf-laravel#144]
I upgraded from 10 to 11. 
Everything works except that he can't find the serializeTCPDFtagParameters function. 
I know that you have to set 'tcpdf_calls_in_html' to true. (It also worked in 10!!) 
But in 11 a new setting was added: 'define('K_ALLOWED_TCPDF_TAGS''). 
The functions that can be called with 'tcpdf_calls_in_html' are listed here. 
I have this line 'define('K_ALLOWED_TCPDF_TAGS', 'serializeTCPDFtagParameters');' added to tcpdf_config.php, but doesn't work. 
I then added the line ''allowed_tcpdf_tags' => 'serializeTCPDFtagParameters',' to /config/tcpdf.php, which doesn't work either. 

What am I doing wrong???? 
Please help quickly because my PDFs no longer work!
for clarity: everything works in 10!!

**Comment by FunctionFan** [comment]
tcpef barcode verson 11.1.0
path: vendor\tecnickcom\tcpdf\tcpdf_autoconfig.php
K_TCPDF_CALLS_IN_HTML = true;
K_ALLOWED_TCPDF_TAGS = '|write1DBarcode|';

examples: https://tcpdf.org/examples/example_049/

**Comment by muhammadessam** [comment]
yes, also here i can't use the config file to override the allowed tags

**Comment by muhammadessam** [comment]
@susanne99 
please check this merge request update packge version in composer should work fine
https://github.com/elibyy/tcpdf-laravel/pull/145
