### ISSUE TITLE
Header & Footer

### ISSUE THREAD

**Issue by johnvic** [elibyy/tcpdf-laravel#15]
Hi, I tried to use the helper function
![image](https://cloud.githubusercontent.com/assets/3714206/18271625/b25702a0-7465-11e6-8df3-1631a52ee366.png)

But not rendering even the Write function for simple text, nothing rendered. Am  I missing something?Please enlighten me.

thanks

**Comment by elibyy** [comment]
hey there,
you should use "```" in order to show code.
also check this one out #9.
also it's not recommended to set full document to header/footer you should set only the block needed such as p,div etc

**Comment by johnvic** [comment]
Hello,

Thanks so much for quick response.
I was missing `PDF::Header();`
Thanks again!

**Comment by johnvic** [comment]
By the way I have an app that is on Laravel 4.2 is the old one could still work on that version?

thanks

**Comment by elibyy** [comment]
I'm sorry but 4.2 was never officially supported by me, i created this package only because i needed this in 5 and no one created that at that time...

sorry about that.
p.s. i think that with little customization of my package you can create something that will support
