### ISSUE TITLE
PDF Output function: Special character in file name not generated

### ISSUE THREAD

**Issue by tejasrsuthar** [elibyy/tcpdf-laravel#16]
Wanted to output filename like below.

Expected File name needs to be created: **Mindre_TS_jobber_Ø.F.pdf**

Current file name created:  **Mindre_TS_jobber_├ÿ.F.pdf**

I'm using below code to generate pdf file.

```
$pdf = new PDF($orientation = 'P', $unit = 'in', $format = 'A4', $unicode = false, $encoding = 'UTF-8', $diskcache = false, $pdfa = false);

$pdf::SetPrintHeader(false);
$pdf::SetPrintFooter(false);
$pdf::AddPage();

$viewData = view($this->view, $this->data)->render();
$pdf::writeHTML($viewData);

$filename = storage_path($this->storagePathInternal) . $this->fileName;
$pdf::output($filename, 'F');
$pdf::reset();
```

Would you guys please help me getting this resolved?

Thanks,

**Comment by elibyy** [comment]
I'm sorry, this is unrelated to my library but directly to how php handles settings files with that kind of name

**Comment by tejasrsuthar** [comment]
Ah ok, thanks for the reply. 

Do you think its php related issue of file generation or TCPDF?

**Comment by elibyy** [comment]
i'm not really sure, you can try and run `file_put_contents($name,'test')` and check the results

**Comment by tejasrsuthar** [comment]
Hello Elibyy,

I run simple test with below code in my pc and its working fine. I need to decode utf8 string. 

```
$f = fopen(utf8_decode('Mindre TS jobber Ø.F.txt'), 'w+');
fwrite($f, 'test');
fclose($f);
```

Without decode it was same garbage character. 

So, I believe, with utf8 decode, that pdf file should generate proper file name.  

```
$filename =  utf8_decode($this->fileName);
```

**Comment by tejasrsuthar** [comment]
Did test with file_put_contents it gave me below results.

Without utf8_decode **Mindre TS jobber Ã˜.F.txt** 
With utf8_decode **Mindre TS jobber Ø.F.txt**

**Comment by tejasrsuthar** [comment]
In my PDF generation code I got below result with utf8_decode.

**Mindre_TS_jobber_Ï.F-22.08.2016.pdf**

It looks like, tcpdf is not decoding UTF8 strings properly.

**Comment by elibyy** [comment]
I'm sorry, but my library is only a wrapper for TCPDF
