### ISSUE TITLE
Move fonts folder to app directroy

### ISSUE THREAD

**Issue by ghost** [elibyy/tcpdf-laravel#17]
Hi ,

I'm trying to move fonts directory to app folder because I have some custome fonts

I change config file and change font directory but still have error

this is my config file

```
<?php
return [
    'font_directory'        => app_path('fonts'),
    'image_directory'       => '',
];
?>
```

the fonts folder located in app folder /home/myuser/myproject/app/fonts
and the error is 

`TCPDF ERROR: Could not include font definition file: helvetica
`
so , I need your help to solve this problem

**Comment by elibyy** [comment]
this error is related to TCPDF and not my library, but i think you should copy the original TCPDF fonts into your directory

**Comment by ghost** [comment]
I copy the original TCPDF fonts into my directory , the error still hapen.

thanks @elibyy

**Comment by A-Ghorab** [comment]
make it app_path('fonts/') it will solve the issue

**Comment by ghost** [comment]
Thanks @AhmedGoGo  you'r right.

it works.
