### ISSUE TITLE
tcpdf.php throws error if HTML has 2 HREFs in it

### ISSUE THREAD

**Issue by OliverGrimsley** [elibyy/tcpdf-laravel#19]
I am using Laravel 5.3 and the current version of this wrapper.  Not sure if this is an error in this wrapper, or the underlying library for tcpdf.  But I think it is this wrapper because I am converting a static app to laravel and tcpdf works in my static app, and also, the tcpdf example pages have html data with multiple links in it.

I have now tested this in many ways, and if I have HTML data to convert to pdf that has 2 links in the data e.g. something like this: 

```html
<p>Lorem ipsum dolor sit amet <a href="http://www.somelink.com/">link</a>
consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et 
dolore magna aliqua <a href="http://www.somelink2.com/">link2</a> etc...</p>
```
I always get a failure throwing the error:  `ErrorException in tcpdf.php line 18807: Illegal string offset 'url'`

But, if I have HTML data with just one href link in it, the PDF resolves fine.

Line 18807 in tcpdf.php is:
```php
$this->HREF['url'] = $tag['attribute']['href'];
```

The code near there in tcpdf.php is:
```php
case 'a': {
    if (array_key_exists('href', $tag['attribute'])) {
	$this->HREF['url'] = $tag['attribute']['href'];
    }
    break;
}
```
I do not think this will matter, but my PDF generating code (sans the actual html) is:
```php
      PDF::SetTitle('Title of PDF');
      PDF::SetFont('times', '', 11);
      PDF::AddPage();
      $image = public_path().'/images/logo.jpg';
      PDF::Image($image,
        $x = '10',
        $y = '10',
        $w = 75,
        $h = 0,
        $type = 'JPG',
        $link = '',
        $align = 'N',
        $resize = false,
        $dpi = 300,
        $palign = 'L',
        $ismask = false,
        $imgmask = false,
        $border = 0,
        $fitbox = false,
        $hidden = false,
        $fitonpage = false,
        $alt = false,
        $altimgs = array());
      PDF::WriteHTML($docbody);
      PDF::writeHTMLCell(120, 0, '', '', $html, '', 1, 0, true, 'R', true);
      $attachment = storage_path().'/filelocation/'.$var->name.'_'.date("F j, Y").'.pdf';
      PDF::Output($attachment,'FI');
```

**Comment by elibyy** [comment]
hey. sorry to hear you having problems. I truly think this might be difference in the tcpdf version. As you could inspect my wrapper's code it is only provides easy way to use within laravel. Let me know and provide some reproducible code so i can try and fix

**Comment by OliverGrimsley** [comment]
The version is the current TCPDF version (6.2.12), however, this could be that this web server is running PHP 7.1 or some other environment specific issue.  I see TCPPDF requires 5.3+  Active linking is not critical to this App right now, until I determine what to do.  The links can just be text.  Everything else works.  Weird.

**Comment by elibyy** [comment]
cannot really reproduce, works fine in my environment but i can perform some extra tests, in my opinion TCPDF doesn't work properly on php 7, but as it seems they are working on a new version, sorry i can't help much, because i only wrapped it

**Comment by elibyy** [comment]
hey @OliverGrimsley,
did you figure out if this issue is caused from my wrapper or from TCPDF?

**Comment by elibyy** [comment]
This issue is closed due to no response, if you have any additions please re-open this issue.

**Comment by wturrell** [comment]
Came across this problem while using TCPDF with WordPress, so for the record I think this is a TCPDF problem and specific to PHP 7.0 or 7.1 (I don't get it in 5.6).  TCPDF is no longer receiving updates, but it's replacement [tc-pdf](https://github.com/tecnickcom/tc-lib-pdf) is not ready yet.

**Comment by dotnet54** [comment]
i am having the same issue, it breaks for <a> tags, where there is one <a> tag it works, but breaks on multiple <a> tags
![screen shot 2017-02-07 at 10 44 06 am](https://cloud.githubusercontent.com/assets/2588566/22679246/6fefddf2-ed22-11e6-89e0-67c4649d4768.png)

**Comment by elibyy** [comment]
sorry that i cannot help, but so it seems (the previous messages within this thread) TCPDF is not working properly on PHP 7 and [tc-pdf](https://github.com/tecnickcom/tc-lib-pdf) is an ongoing migration of TCPDF, I'm keeping my eye on the release of the tc-pdf and will create a new package to allow usage of the new lib

**Comment by JorisDebonnet** [comment]
Note that it is fixed on tecnickcom/tcpdf dev-master. 

(I have emailed the author to ask for a new release, but not sure how quickly he would reply)

**Comment by paoga87** [comment]
Hello,

I am having the same issue TCPDF v. 6.2.13. My local env is using PHP v. 7.2.4. The error comes up as many times as there are `a href` tags on the html code, and just to reiterate, when there's only one `a href ` tag, then the page renders correctly.

I am just curious if there can be a quick fix on the code block of tcpdf.php?

```php
case 'a': {
    if (array_key_exists('href', $tag['attribute'])) {
	$this->HREF['url'] = $tag['attribute']['href'];
    }
    break;
}
```

Thanks,
-Paola G.

**Comment by elibyy** [comment]
Hey @paoga87 
You should update your tecnickcom/TCPDF to the latest version and that should fix the issue.
Please let me know if that solved the problem.

Eli

**Comment by paoga87** [comment]
@elibyy it did... I did not realize I had downloaded an older version after going through the docs. Thank you!

**Comment by neerajs046** [comment]
![image](https://user-images.githubusercontent.com/11793604/46430430-8b274b80-c766-11e8-8ac2-f9e5479efc08.png)

Getting this error. It was working fine earlier but now getting this error

**Comment by elibyy** [comment]
Hey @neerajs046, It's unclear what are you doing that let to this error.
Please open a new issue with details of the error

Thanks

**Comment by garyfalos** [comment]
Hey @elibyy, I think that I solved the issue (at least for me)!!!
I'm running PHP Version 7.4.1 on xampp installed in MS Windows 10 x64 (1909). I wanted to embody tcpdf in opencart-3.0.3.2 framework. The error I got from server was 

> Warning: Illegal string offset 'url' in C:\xampp\htdocs\opencart\admin\controller\extension\invoice\tcpdf-master\tcpdf.php on line 18807
TCPDF ERROR: Some data has already been output, can't send PDF file

so I changed 
```php
	case 'a': {
		if (array_key_exists('href', $tag['attribute'])) {
		$this->HREF['url'] = $tag['attribute']['href'];
		}
	break;
	}
```
to
```php		
	case 'a': {
		if (array_key_exists('href', $tag['attribute'])) {
			if(!empty($this->HREF) AND (isset($this->HREF['url']))){
				$this->HREF['url'] = $tag['attribute']['href'];
			}
		}
	break;
	}
```
the link www.tcpdf.org at the top of example_001.php works perfectly!!!

**Comment by jonathanjiang1216** [comment]
There seems to be another place in the code where an empty string has been assigned to $this->HREF.  I made the following change and it seems to solve the problem.

On line 19756:  
            case 'a': {
                    $this->HREF = [];	// 2020-05-15 changed '' to empty array []
                    break;
                }
