### ISSUE TITLE
Update to Laravel 5.4

### ISSUE THREAD

**Issue by sirikkoster** [elibyy/tcpdf-laravel#20]
"illuminate/support": "5.3.x", is blocking the update to Laravel 5.4

**Comment by elibyy** [comment]
hey there,
haven't seen the release notes yet, will update ASAP

**Comment by sirikkoster** [comment]
thnx

**Comment by elibyy** [comment]
https://github.com/elibyy/tcpdf-laravel/releases/tag/5.4.0
