### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by it-can** [elibyy/tcpdf-laravel#22]
Hi when creating a PDF (in a queue job), I get this error sometimes:

```
Undefined property: Elibyy\TCPDF\TCPDFHelper::$font_subsetting
```

Happens when setting a font like this

```
PDF::SetFont('helvetica', '', 11);
```

**Comment by elibyy** [comment]
as far as i know, tcpdf is destroying the class after the `output` call, that's why I've added the `reset` method, let me know if this is the problem

**Comment by it-can** [comment]
Uuhm ok but the output is after the setfont call

**Comment by it-can** [comment]
So where do i need to call the reset method?

**Comment by elibyy** [comment]
i will need to see more code to be sure, are you looping and creating PDF's or only one?

**Comment by it-can** [comment]
Just once, the weird thing is this error is only generated when using it in a queue job, when calling it direclty in the code it works without errors...

**Comment by elibyy** [comment]
try calling PDF::reset before anything

**Comment by it-can** [comment]
Ok will try this afternoon thanks for the help

**Comment by it-can** [comment]
Seems to work thanks
