### ISSUE TITLE
setHeaderCallback() not on first page

### ISSUE THREAD

**Issue by basvandertogt** [elibyy/tcpdf-laravel#23]
Is it possible to remove the header from the first page?

**Comment by elibyy** [comment]
how about 
```
PDF::setHeaderCallback(function($pdf){
     if($pdf->getPage() == 0){}
}
```

**Comment by basvandertogt** [comment]
The last time i tried this it did not work. But now i figured out that my first page with a table of contents has page number 6 in stead of 0. Tnx for your reply!
