### ISSUE TITLE
Problem with laravel 5.4

### ISSUE THREAD

**Issue by martille2** [elibyy/tcpdf-laravel#28]
I have a problem with laravel 5.4
When i add tcpdf and run composer update, i receive this error
    - The requested package elibyy/laravel-tcpdf 5.4.* exists as elibyy/laravel-tcpdf[5.1.x-dev, dev-master, v0.0.1, v0.0.2, v0.0.3, v0.0.4, v0.0.5, v0.0.6] but these are rejected by your constraint.

**Comment by elibyy** [comment]
hey there,
please note that *laravel-tcpdf* is the old package and is replaced with *tcpdf-laravel* (inverted keywords)

**Comment by martille2** [comment]
thank you
