### ISSUE TITLE
Config not loading

### ISSUE THREAD

**Issue by it-can** [elibyy/tcpdf-laravel#3]
It seems the config is not loading in 5.2, when I add the tcpdf.php file to my confg dir...

**Comment by it-can** [comment]
it seems `laravel-tcpdf` config is not found in https://github.com/elibyy/tcpdf-laravel/blob/master/src/TCPDF.php#L24

?

**Comment by elibyy** [comment]
it seems like my mistake while migrating from the old project i will fix it ASAP

**Comment by it-can** [comment]
(Y)
