### ISSUE TITLE
TCPDF Custom Font

### ISSUE THREAD

**Issue by MohanrajSecqureone** [elibyy/tcpdf-laravel#32]
Hi,
please help me how to add a custom font in TCPFD Laravel

thanks.

**Comment by elibyy** [comment]
hey there,
please check out [this](https://stackoverflow.com/questions/5263588/how-to-implement-custom-fonts-in-tcpdf) and [this](https://github.com/elibyy/tcpdf-laravel/issues/17)

since my wrapper is only a binding to TCPDF
