### ISSUE TITLE
Output($tmp_file, 'F') using Job dispatched to queue.

### ISSUE THREAD

**Issue by faralimite** [elibyy/tcpdf-laravel#34]
Hello,

I need to have a job dispatched to queue in order to generate a big pdf. First time when the job is dispatched I have this error:
<strong>TCPDF ERROR: </strong>Empty font family

After the retries mechanism starts it works.

Regards,
Radu

**Comment by elibyy** [comment]
Hello,
sorry for the delayed response
can you provide related code that contains the call to `AddFont` and some context for where is it being called

**Comment by elibyy** [comment]
@faralimite This issue is being close due to noe response
you can always re-open it :)
