### ISSUE TITLE
Version 5.5 doesn't work with laravel 5.3

### ISSUE THREAD

**Issue by nieka** [elibyy/tcpdf-laravel#35]
When i tried to install the newest version of this composer package i got the following error messages:
`
Problem 1
    - Conclusion: don't install elibyy/tcpdf-laravel 5.5.1
    - Installation request for elibyy/tcpdf-laravel ^5.5 -> satisfiable by elibyy/tcpdf-laravel[5.5.0, 5.5.1].
    - Conclusion: remove laravel/framework v5.3.31
    - elibyy/tcpdf-laravel 5.5.0 requires illuminate/support 5.5.* -> satisfiable by illuminate/support[v5.5.0, v5.5.2].
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.3.31
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.3.31
    - Installation request for laravel/framework (installed at v5.3.31, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.31].
`

When i installed version 5.3 it worked. 
Is this intented that the laravel  version needs to be te same as the tcpdf-laravel package version?

(Sorry for the bad english)

**Comment by elibyy** [comment]
Hello there,
sorry for the delayed response
as noted in the README file `Note: The versions are now as laravel 5.x`
so the version pattern in the composer json should be `5.3.*`

hope this will help
