### ISSUE TITLE
Class 'PDF' not found in Lumen

### ISSUE THREAD

**Issue by mmartinello** [elibyy/tcpdf-laravel#36]
I am using the **5.2** version on **Lumen 5.4.7**, i registered the class with

```
$app->withFacades();
$app->register(Elibyy\TCPDF\ServiceProvider::class);
```

but my route returns me this error

```
Fatal error: Class 'PDF' not found in /Users/m/Documents/Projects/pdf/app/Http/Controllers/PdfController.php on line 15
(1/1) FatalErrorException
Class 'PDF' not found
in PdfController.php (line 15)
at Application->handleShutdown()
in RegistersExceptionHandlers.php (line 54)
at Application->Laravel\Lumen\Concerns\{closure}()
```

I am wondering if I missing something but I read the documentation at https://github.com/elibyy/tcpdf-laravel/tree/5.4.2 and I followed what is written at **"for lumen you should add the following line"**.

**Comment by mmartinello** [comment]
I solved my problem.
One line was missing into `bootstrap/app.php` to add a new **class_alias** for `Elibyy\TCPDF\Facades\TCPDF` to `PDF`:

```
class_alias('Elibyy\TCPDF\Facades\TCPDF', 'PDF');`
```

I think this should be added into the README file.

Thanks!

**Comment by elibyy** [comment]
@decibel83 thank you, I've updated the README file
