### ISSUE TITLE
Laravel 5.5 with PHP 7.2.0 - The each() function is deprecated. This message will be suppressed on further calls

### ISSUE THREAD

**Issue by jcrodyar87** [elibyy/tcpdf-laravel#37]
Hello, I'm developing a project with laravel and php version 7.2.0. When i tried create my PDF file using tcpdf, i had this message

`The each() function is deprecated. This message will be suppressed on further calls`

And the message showed is related to the next file at lines 16548 and 16561

`vendor\tecnickcom\tcpdf\tcpdf.php`

```
16548 while (list($id, $name) = each($attr_array[1])) {

16561 while (list($id, $name) = each($attr_array[1])) {
```
I replaced the line with the next code in both lines and it worked

`foreach($attr_array[1] as $id => $name) {`

If it is rigth and it is useful, add the change at project else i hope the right fix. 

Thank you so much!

**Comment by elibyy** [comment]
Hey there,
as specified in the README file, TCPDF is not really supported in PHP 7, and since I'm not part of TCPDF dev team, there's not much that i can do.

TCPDF has plans to support PHP 7 using a new [lib](https://github.com/tecnickcom/tc-lib-pdf)
whenever they release the new lib, my wrapper will be modified to support the new lib

sorry about that

**Comment by acirinelli** [comment]
There is an issue open on this that just needs to be merged:
https://github.com/tecnickcom/TCPDF/pull/74

This is causing a ton of problems for me as my app relies heavily on PDFs.

**Comment by elibyy** [comment]
Hey there,
Since i don't control TCPDF lib in anyway will push an override that will fix this specific error
Hope it will help

Check out the new releases and let me know :)

**Comment by acirinelli** [comment]
@elibyy Tested and working, thank you so much!

**Comment by abdulrauf618** [comment]
latest: https://github.com/DALTCORE/lara-pdf-merger
