### ISSUE TITLE
Config tcpdf.php wrong variable "page_units"

### ISSUE THREAD

**Issue by acirinelli** [elibyy/tcpdf-laravel#38]
I spent hours trying to figure out why the margins were not changing per the config file and then I discovered this minor discrepancy:

The package's TCPDFHelper calls "Config::get('tcpdf.page_unit', 'mm')," as the default ,while the config tcpdf.php file calls out "page_units" (plural)

So what I thought was 0.5in was really 0.5mm, basically zero margins.

**Comment by elibyy** [comment]
@acirinelli Thanks for your report
The issue was fixed and pushed a new release.

Please let me know if there's any other issues
