### ISSUE TITLE
How to change page_orientation to Horizontal

### ISSUE THREAD

**Issue by sxilo-kek** [elibyy/tcpdf-laravel#39]
or just how to make more large width, cause I'm trying to print 18 column table data, please help

**Comment by elibyy** [comment]
Hey there,
as part of the configurations there's page size and page orientation options.
if you haven't already, you should run `artisan vendor publish` that will add the tcpdf.php config file

please let me know if there's any other issues

**Comment by sxilo-kek** [comment]
I mean sir how do I change / 'page_orientation'      => 'A', / . to horizontal sir.

**Comment by elibyy** [comment]
if you ran the previous command, there should be a tcpdf.php file in your config directory, within that file 
you can set page_orientation = L for landscape or even change the page_format from A4 to A3

**Comment by sxilo-kek** [comment]
Thank you, sir. bless you ;)
