### ISSUE TITLE
TCPDF functions missing?

### ISSUE THREAD

**Issue by matiasah** [elibyy/tcpdf-laravel#43]
![image](https://user-images.githubusercontent.com/5008893/36396705-37059ac2-159e-11e8-8dcd-5a63b567c061.png)
![image](https://user-images.githubusercontent.com/5008893/36396740-6055f0a2-159e-11e8-8b85-05b6cf57a646.png)
![image](https://user-images.githubusercontent.com/5008893/36396763-771b14e8-159e-11e8-9034-a729c3cde3a0.png)
![image](https://user-images.githubusercontent.com/5008893/36396778-83045dd2-159e-11e8-8088-123e112a6869.png)
I'm having some issues with the library, I'm not sure if I'm doing anything wrong. It also throws errors when trying to use any other method; SetTitle, SetAuthor, AddPage, etc.

**Comment by elibyy** [comment]
Hey there,
if you are using the facade pattern you are not suppose to do `new TCPDF()` but instead `TCPDF::Output('boleta.pdf','I')` and so on

Please note that if you intend on generating more than one PDF you should use the `reset` method

Hope this helps

**Comment by matiasah** [comment]
![image](https://user-images.githubusercontent.com/5008893/36397434-878b516e-15a1-11e8-9b72-75f49152b1b3.png)
![image](https://user-images.githubusercontent.com/5008893/36397444-9206cb5a-15a1-11e8-898b-0f8145f37eff.png)
I can't seem to be getting it either way.

**Comment by elibyy** [comment]
That's odd.
Can you please try and provide the following:
* The evaluation of the expression  `dd(get_class($this->tcpdf));` by temporarily adding it in D:\Git\GetFit\Backend\vendor\elibyy\tcpdf-laravel\src\TCPDF.php on line 38
* The version of tecnickcom/tcpdf from composer.lock

Also, The reset is only required at the end and only if you are in a loop, by default there's no need for it

**Comment by matiasah** [comment]
![image](https://user-images.githubusercontent.com/5008893/36398818-b37bf444-15a7-11e8-80c2-0d1552673115.png)
That's the output, doesn't seem to be null.

![image](https://user-images.githubusercontent.com/5008893/36398901-11ec7cba-15a8-11e8-8694-4f339ba8d386.png)

**Comment by matiasah** [comment]
Now, I renamed the 'TCPDF' alias to just 'PDF'. I don't know why, but it fixes the issue.

**Comment by elibyy** [comment]
Yup, just figured it out too.
Apparently PHP allows you to override classes using `class_alias` (which laravel uses internally for anything you specify in aliases array in config/app.php).
So my `class TCPDFHelper extends \TCPDF` translates into `class TCPDFHelper extends \Elibyy\TCPDF\Facades\TCPDF`
that doesn't have the method `AddPage`
