### ISSUE TITLE
Store PDF file on Amazon S3

### ISSUE THREAD

**Issue by jringeisen** [elibyy/tcpdf-laravel#47]
I am using TCPDF to convert a view into a PDF, then I want to store the PDF to an S3 bucket. I can't figure out to do this properly.

Below is the snippet of code I have been trying. The problem is how do I get the contents of the file to include in the $contents variable?

If I replace $contents with a string it pushes it to my s3 bucket but the file is corrupt and I assume that's because it's not sending the file contents.

`PDF::output(Storage::disk('s3')->put($user->contractDir() . '/contract.pdf', $contents, 'public'), 'F');`

**Comment by jringeisen** [comment]
I was able to get it to work by storing it on my local machine and then pushing it to amazon s3. Is there a way to avoid storing it on my local storage and storing it straight to amazon s3?

**Comment by jringeisen** [comment]
Here is what I did to make it work:

     $fileName = 'contract-' . time() . '.pdf';
     $filePath = storage_path('app') . '/contracts/' . $fileName;

     $pdf = new PDF;
     $pdf::SetPrintHeader(false);
     $pdf::SetPrintFooter(false);
     $pdf::AddPage();
     $pdf::writeHTML(view('users.clients.contract.show', compact('client_contract', 'user'))->render(), true, false, true, false, '');
     $pdf::SetProtection(['modify', 'copy', 'annot-forms', 'extract', 'assemble', 'print-high'], 
     $client_contract->password, $user->email, 3);
     $file = $pdf::output($filePath, 'F');

     Storage::disk('s3')->put($user->contractDir() . $fileName, file_get_contents($filePath), 'public');

     unlink($filePath);

I am sure there is a better solution. With this, I have to store it to my local storage then pass the file to S3 then delete it from local storage. There should be a way to shoot it over to s3 without storing it locally. But this will work until I can figure out something else.

**Comment by elibyy** [comment]
Hey there,
If I understand correctly, you should simply use S as the dest parameter in the output method, then file variable will have the PDF contents. And then you can skip the `file_get_contents` call, and it won't store the file on the server.

**Comment by jringeisen** [comment]
@elibyy that did it. I just had to remove the `file_get_contents()`.

Here is the final bit of code in case anyone needs help in the future. 

    $fileName = 'contract-' . time() . '.pdf';

    $pdf = new PDF;
    $pdf::SetPrintHeader(false);
    $pdf::SetPrintFooter(false);
    $pdf::AddPage();
    $pdf::writeHTML(view('users.clients.contract.show', compact('client_contract', 'user'))->render(), true, false, true, false, '');
    $pdf::SetProtection(['modify', 'copy', 'annot-forms', 'extract', 'assemble', 'print-high'], $client_contract->password, $user->email, 3);
    $file = $pdf::output($fileName, 'S');

    Storage::disk('s3')->put($user->contractDir() . $fileName, $file, 'public');

**Comment by elibyy** [comment]
@jringeisen Seems about right, but you don't really need to set the filename in the output method.

Also can i close this issue as it seems the problem as resolved?

**Comment by jringeisen** [comment]
@elibyy ahh I see. Yes, this has been resolved. Thank you!

**Comment by elibyy** [comment]
So just to clarify, here the final code:

```php
\PDF::SetPrintHeader(false);
\PDF::SetPrintFooter(false);
\PDF::AddPage();
\PDF::writeHTML(view('users.clients.contract.show', compact('client_contract', 'user'))->render(), true, false, true, false, '');
\PDF::SetProtection(['modify', 'copy', 'annot-forms', 'extract', 'assemble', 'print-high'], $client_contract->password, $user->email, 3);
$fileContents = \PDF::output('', 'S'); // name is ignored here
```

Please note that I've also replaced $pdf with The actual class name because this is what facade is for :)
