### ISSUE TITLE
setProtection() doesn't work with PHP 7.1.3

### ISSUE THREAD

**Issue by jringeisen** [elibyy/tcpdf-laravel#48]
I am currently running Laravel 5.6 with PHP 7.1.3 and everything works except when I use setProtection(). I get the following error:

`mcrypt_get_cipher_name() is deprecated`

Is there a workaround for this?

**Comment by elibyy** [comment]
Hey there,
this is due to your `error_reporting` configuration. check [this](https://stackoverflow.com/questions/18497788/laravel-breaks-entire-app-on-php-notices) out

**Comment by jringeisen** [comment]
@elibyy I will take a look, it was working fine in my local development environment but once I pushed it to production this started happening.

**Comment by jringeisen** [comment]
@elibyy perfect! I added `error_reporting(0);` to app\Providers\AppServiceProvider inside the boot() method.

**Comment by elibyy** [comment]
@jringeisen Just to ensure you are familiar, error_reporting is not scope based, so if you disabled it there it will be disabled in all of your application unless reactivated, the recommended PHP value for this in production is `E_ALL & ~E_DEPRECATED & ~E_STRICT`
