### ISSUE TITLE
startPageGroup doesn't work

### ISSUE THREAD

**Issue by martille2** [elibyy/tcpdf-laravel#49]
Please i need to restart the page number in the pdf but the startPageGroup doesn't work.
Can you help me?

**Comment by elibyy** [comment]
Hello @martille2,
Just to acknowledge I do not maintain TCPDF, my library is a wrapper for it in Laravel, so if you have any issues regarding TCPDF, you should check their docs.

Also, please provide code examples

Thanks

**Comment by martille2** [comment]
is only not clear the example 23 of tcpdf.
For the correct use of  the page group is necessary to use getPageNumGroupAlias() and getPageGroupAlias()
instead of
getAliasNumPage() and getAliasNbPages()
