### ISSUE TITLE
fpdi or similar

### ISSUE THREAD

**Issue by martille2** [elibyy/tcpdf-laravel#50]
I need to add to my pdf, some other pdf. There is the possibility to do this?

Can you help me ?

thanks

**Comment by elibyy** [comment]
Hey @martille2,
Sorry for the delayed response, please check [this release](https://github.com/elibyy/tcpdf-laravel/releases/tag/5.6.2).

**Comment by martille2** [comment]
Thank you very very much

**Comment by mmartinello** [comment]
Thanks @elibyy, I also need to use FPDI with TCPDF, but I’m using Lumen, how to add use_fpdi option parameter?
Thank you very much!
