### ISSUE TITLE
setHeaderCallback cuts text vertically

### ISSUE THREAD

**Issue by giacomomasseron** [elibyy/tcpdf-laravel#51]
Hi,  
with this simple code:  

    PDF::setHeaderCallback(function($pdf) {
		$pdf->SetFont('helvetica', 'B', 20);
		// Title
		$pdf->Cell(0, 15, '<< TCPDF Example 003 >>', 0, false, 'C', 0, '', 0, false, 'M', 'M');
	});

	PDF::AddPage();
	PDF::Write(0, 'Hello World');
	PDF::Output($codice . '.pdf');

I get this PDF:
![schermata a 2018-03-29 11-17-09](https://user-images.githubusercontent.com/16156317/38080901-fd4b3856-3342-11e8-8145-661ed8c1689b.png)

Same if I add footer.
What I am doing wrong?

**Comment by elibyy** [comment]
Hey,
I don't think it's related to the `headerCallback`.
It seems you've missed the image from the example
```
$image_file = K_PATH_IMAGES.'logo_example.jpg';
		$pdf->Image($image_file, 10, 10, 15, '', 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
```
which pushes is to position
![image](https://user-images.githubusercontent.com/836551/38083435-445cd9b6-3352-11e8-9105-ab1ae612d83b.png)

**Comment by giacomomasseron** [comment]
You right, I solved with an image.
