### ISSUE TITLE
Default Header and Footer

### ISSUE THREAD

**Issue by NanoDev777** [elibyy/tcpdf-laravel#52]
I would like to know how, I can use the default header and footer format, as shown on the tcpdf page: https://tcpdf.org/examples/example_001/ I could not do it.

**Comment by elibyy** [comment]
Hey there,
Currently it's not possible to use the default header/footer because my library overrides it.
I will try to add this capability ASAP.
but for now you can use.
`PDF::setHeaderCallback(function($pdf){})`
or
`PDF::setFooterCallback(function($pdf){})`

**Comment by elibyy** [comment]
Please checkout this [release](https://github.com/elibyy/tcpdf-laravel/releases/tag/5.6.2)

**Comment by SleepingProgrammer** [comment]
Hi @elibyy how do I use the use_original_header? Thanks!

**Comment by SleepingProgrammer** [comment]
> 
> 
> Hi @elibyy how do I use the use_original_header? Thanks!

Nevermind I saw it.
Had to publish config first.

Thanks for this awesome wrapper!

**Comment by farmaworld** [comment]
Sorry but I'm a newbie, I installed this fantastic library on my Laravel and everything works, but I still haven't figured out how to manage my custom Footer. as i can't instantiate a new class in my Laravel controller, how do i just put a text in the footer
Thank you
