### ISSUE TITLE
How to set custom page format and orientation?

### ISSUE THREAD

**Issue by drpshtiwan** [elibyy/tcpdf-laravel#53]
I checked the TCPDF class there is a method
```php
public static function changeFormat($format)
{
    static::$format = $format;
}
```

but when I use it, it is not working.
```php
PDF::changeFormat('A6');
PDF::SetTitle('Sample PDF');
PDF::AddPage();
PDF::SetFont('dejavusans', '', 12);
PDF::writeHTML($html_content, true, 0, true, 0);
PDF::setRTL(false);
```

How to override the default configs? I want to use multiple sizes

**Comment by elibyy** [comment]
you should do
```php
PDF::changeFormat('A6');
PDF::reset();
```

Which will create a new instance of TCPDF.

Please let me know if that worked
Eli

**Comment by drpshtiwan** [comment]
Great, it worked fine thanks... As a suggestion if you add changeOrientation method to the class it will be the best... something like this
```php
protected static $orientation;

public function reset()
{
    $class = Config::get('tcpdf.use_fpdi') ? FpdiTCPDFHelper::class : TCPDFHelper::class;

    $this->tcpdf = new $class(
        static::$orientation ? static::$orientation : Config::get('tcpdf.page_orientation', 'P'),
        Config::get('tcpdf.page_units', 'mm'),
        static::$format ? static::$format : Config::get('tcpdf.page_format', 'A4'),
        Config::get('tcpdf.unicode', true),
        Config::get('tcpdf.encoding', 'UTF-8')
    );
}

public static function changeOrientation($orientation)
{
    static::$orientation = $orientation;
}
```

**Comment by Mox90** [comment]
Sir, I also would like to ask how can i set the page size into smaller for bar code label sticker?

**Comment by elibyy** [comment]
Hey @Mox90,
You can use the config `tcpdf.page_format`
You can check [here](https://github.com/tecnickcom/TCPDF/blob/master/include/tcpdf_static.php#L2107) for available formats

**Comment by PeterTough2** [comment]
@elibyy I want to make an image to cover the entire page with no margins or header for some individual pages in PDF.

Any idea how that can be achieved
