### ISSUE TITLE
The each() function is deprecated. This message will be suppressed on further calls

### ISSUE THREAD

**Issue by marafatcis** [elibyy/tcpdf-laravel#54]
The each() function is deprecated. This message will be suppressed on further calls

**Comment by marafatcis** [comment]
please how can i solve this problem

**Comment by elibyy** [comment]
Hey there,
Please provide more information such as version of the library and version of TCPDF
As far as i know in the latest version of TCPDF it's fixed.

Please let me know if there's anything else

**Comment by marafatcis** [comment]
I installed the latest version

**Comment by marafatcis** [comment]
i installed this :
https://github.com/elibyy/tcpdf-laravel

{
    "require": {
        "elibyy/tcpdf-laravel": "5.6.*"
    }
}

**Comment by elibyy** [comment]
Ok, this doesn't really provide enough information, so if you could run `composer show`
It will generate a list of packages in your project and their versions.
if you could provide the version of `tecnickcom/tcpdf` and `elibyy/tcpdf-laravel` from the list.
The expected values are: 
tecnickcom/tcpdf = 6.2.17
elibyy/tcpdf-laravel = 5.6.2
if the values are different, you should try running `composer update`

Please let me know if there's anything else i can help
Eli

**Comment by marafatcis** [comment]
i solved it with myself but this is new error 
TCPDF ERROR: [Image] Unable to get the size of the image: http://127.0.0.1:8000/images/logo.png

**Comment by marafatcis** [comment]
i want to include images

**Comment by elibyy** [comment]
Hey there,
again, you should provide more info, such as sample code, so that I would be able to assist and try to reproduce.

It seems that `file_get_contents` is unable to fetch your file from the specified URL
you should try and place the image in a real file path instead

**Comment by marafatcis** [comment]
i want to include images in the pdf file

**Comment by yenyint** [comment]
"The each() function is deprecated" problem is occur in php 7.2.

**Comment by elibyy** [comment]
Hey @nyeyint,
Please provide more information such as version of the library and version of TCPDF
As far as i know in the latest version of TCPDF it's fixed.

Please let me know if there's anything else

**Comment by DimitriAcostaOrderOS** [comment]
I was also having trouble with this package on php 7.2, so I downgraded to php 7.1 and it's now working perfectly fine, I guess this package is not yet compatible with php 7.2

**Comment by elibyy** [comment]
This issue is being close due to no further response

**Comment by dabarlea** [comment]
Hi, My composer.json is the following:

> {
>     "name": "laravel/laravel",
>     "description": "The Laravel Framework.",
>     "keywords": ["framework", "laravel"],
>     "license": "MIT",
>     "type": "project",
>     "require": {
>         "php": ">=5.5.9",
>         "laravel/framework": "5.2.*",
>         "laravelcollective/html": "5.2.*",
>         "barryvdh/laravel-debugbar": "~2.4",
>         "elibyy/tcpdf-laravel":"5.2.*"
>     },
>     "require-dev": {
>         "fzaninotto/faker": "~1.4",
>         "mockery/mockery": "0.9.*",
>         "phpunit/phpunit": "~4.0",
>         "symfony/css-selector": "2.8.*|3.0.*",
>         "symfony/dom-crawler": "2.8.*|3.0.*"
>     },
>     "autoload": {
>         "classmap": [
>             "database"
>         ],
>         "psr-4": {
>             "Sistema\\": "app/"
>         }
>     },
>     "autoload-dev": {
>         "classmap": [
>             "tests/TestCase.php"
>         ]
>     },
>     "scripts": {
>         "post-root-package-install": [
>             "php -r \"copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "php artisan key:generate"
>         ],
>         "post-install-cmd": [
>             "Illuminate\\Foundation\\ComposerScripts::postInstall",
>             "php artisan optimize"
>         ],
>         "post-update-cmd": [
>             "Illuminate\\Foundation\\ComposerScripts::postUpdate",
>             "php artisan optimize"
>         ]
>     },
>     "config": {
>         "preferred-install": "dist"
>     }
> }



I used example 1 of TCPDF.org and got the following message:

> ErrorException in tcpdf.php line 16542:
> The each() function is deprecated. This message will be suppressed on further calls


If I use the versions you recommend:
tecnickcom/tcpdf = 6.2.17
elibyy/tcpdf-laravel = 5.6.2
, and make composer update, i got the following messege in terminal:


> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - elibyy/tcpdf-laravel 5.2.9 requires tecnickcom/tcpdf 6.2.12 -> satisfiable by tecnickcom/tcpdf[6.2.12] but these conflict with your requirements or minimum-stability.
>     - elibyy/tcpdf-laravel 5.2.7 requires tecnickcom/tcpdf 6.2.12 -> satisfiable by tecnickcom/tcpdf[6.2.12] but these conflict with your requirements or minimum-stability.
>     - elibyy/tcpdf-laravel 5.2.6 requires tecnickcom/tcpdf 6.2.12 -> satisfiable by tecnickcom/tcpdf[6.2.12] but these conflict with your requirements or minimum-stability.
>     - elibyy/tcpdf-laravel 5.2.5 requires tecnickcom/tcpdf 6.2.12 -> satisfiable by tecnickcom/tcpdf[6.2.12] but these conflict with your requirements or minimum-stability.
>     - elibyy/tcpdf-laravel 5.2.4 requires tecnickcom/tcpdf 6.2.12 -> satisfiable by tecnickcom/tcpdf[6.2.12] but these conflict with your requirements or minimum-stability.
>     - elibyy/tcpdf-laravel 5.2.3 requires tecnickcom/tcpdf 6.2.12 -> satisfiable by tecnickcom/tcpdf[6.2.12] but these conflict with your requirements or minimum-stability.
>     - elibyy/tcpdf-laravel 5.2.2 requires tecnickcom/tcpdf 6.2.12 -> satisfiable by tecnickcom/tcpdf[6.2.12] but these conflict with your requirements or minimum-stability.
>     - elibyy/tcpdf-laravel 5.2.1 requires tecnickcom/tcpdf 6.2.12 -> satisfiable by tecnickcom/tcpdf[6.2.12] but these conflict with your requirements or minimum-stability.
>     - elibyy/tcpdf-laravel 5.2.0 requires tecnickcom/tcpdf 6.2.9 -> satisfiable by tecnickcom/tcpdf[6.2.9] but these conflict with your requirements or minimum-stability.
>     - elibyy/tcpdf-laravel 5.2.9 requires tecnickcom/tcpdf 6.2.12 -> satisfiable by tecnickcom/tcpdf[6.2.12] but these conflict with your requirements or minimum-stability.
>     - Conclusion: remove laravel/framework v5.2.45
>     - Conclusion: don't install laravel/framework v5.2.45
>     - Conclusion: don't install laravel/framework v5.2.44
>     - Conclusion: don't install laravel/framework v5.2.43
>     - Conclusion: don't install laravel/framework v5.2.42
>     - Conclusion: don't install laravel/framework 5.2.41
>     - Conclusion: don't install laravel/framework v5.2.40
>     - Conclusion: don't install laravel/framework v5.2.39
>     - Conclusion: don't install laravel/framework v5.2.38
>     - Conclusion: don't install laravel/framework v5.2.37
>     - Conclusion: don't install laravel/framework v5.2.36
>     - Conclusion: don't install laravel/framework v5.2.35
>     - Conclusion: don't install laravel/framework v5.2.34
>     - Conclusion: don't install laravel/framework v5.2.33
>     - Conclusion: don't install laravel/framework v5.2.32
>     - Conclusion: don't install laravel/framework v5.2.31
>     - Conclusion: don't install laravel/framework v5.2.30
>     - Conclusion: don't install laravel/framework v5.2.29
>     - Conclusion: don't install laravel/framework v5.2.28
>     - Conclusion: don't install laravel/framework v5.2.27
>     - Conclusion: don't install laravel/framework v5.2.26
>     - Conclusion: don't install laravel/framework v5.2.25
>     - Conclusion: don't install laravel/framework v5.2.24
>     - Conclusion: don't install laravel/framework v5.2.23
>     - Conclusion: don't install laravel/framework v5.2.22
>     - Conclusion: don't install laravel/framework v5.2.21
>     - Conclusion: don't install laravel/framework v5.2.20
>     - Conclusion: don't install laravel/framework v5.2.19
>     - Conclusion: don't install laravel/framework v5.2.18
>     - Conclusion: don't install laravel/framework v5.2.17
>     - Conclusion: don't install laravel/framework v5.2.16
>     - Conclusion: don't install laravel/framework v5.2.15
>     - Conclusion: don't install laravel/framework v5.2.14
>     - Conclusion: don't install laravel/framework v5.2.13
>     - Conclusion: don't install laravel/framework v5.2.12
>     - Conclusion: don't install laravel/framework v5.2.11
>     - Conclusion: don't install laravel/framework v5.2.10
>     - Conclusion: don't install laravel/framework v5.2.9
>     - Conclusion: don't install laravel/framework v5.2.8
>     - Conclusion: don't install laravel/framework v5.2.7
>     - Conclusion: don't install laravel/framework v5.2.6
>     - Conclusion: don't install laravel/framework v5.2.5
>     - Conclusion: don't install laravel/framework v5.2.4
>     - Conclusion: don't install laravel/framework v5.2.3
>     - Installation request for elibyy/tcpdf-laravel 5.2.* -> satisfiable by elibyy/tcpdf-laravel[5.2.0, 5.2.1, 5.2.2, 5.2.3, 5.2.4, 5.2.5, 5.2.6, 5.2.7, 5.2.8, 5.2.9].
>     - Conclusion: don't install laravel/framework v5.2.2
>     - Conclusion: don't install laravel/framework v5.2.1
>     - elibyy/tcpdf-laravel 5.2.8 requires illuminate/support 5.6.* -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.0
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.1
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.10
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.11
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.12
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.13
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.14
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.15
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.16
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.17
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.19
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.2
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.20
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.21
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.22
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.23
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.24
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.25
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.26
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.27
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.28
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.29
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.3
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.30
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.31
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.32
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.33
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.34
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.35
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.36
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.37
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.38
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.4
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.5
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.6
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.7
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.8
>     - don't install laravel/framework v5.2.0|don't install illuminate/support v5.6.9
>     - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.41, v5.2.0, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.40, v5.2.42, v5.2.43, v5.2.44, v5.2.45, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9].
> 


Note: if I can generate PDF, the problem is when I want to add custom code within the content, for example:

> // Set some content to print
> $html = <<<EOD
> <h1>Welcome to <a href="http://www.tcpdf.org" style="text-decoration:none;background-color:#CC0000;color:black;">&nbsp;<span style="color:black;">TC</span><span style="color:white;">PDF</span>&nbsp;</a>!</h1>
> <i>This is the first example of TCPDF library.</i>
> <p>This text is printed using the <i>writeHTMLCell()</i> method but you can also use: <i>Multicell(), writeHTML(), Write(), Cell() and Text()</i>.</p>
> <p>Please check the source code documentation and other examples for further information.</p>
> <p style="color:#CC0000;">TO IMPROVE AND EXPAND TCPDF I NEED YOUR SUPPORT, PLEASE <a href="http://sourceforge.net/donate/index.php?group_id=128076">MAKE A DONATION!</a></p>
> EOD;

> 
> // Print text using writeHTMLCell()
> $pdf->writeHTMLCell(0, 0, '', '', $html, 0, 1, 0, true, '', true);




**Copy the code but it is not shown as code because GitHub transforms it. the code I'm referring to is the one from the last part of https://tcpdf.org/examples/example_001/**


**Thanks for your help**

**Comment by manishpanchal** [comment]
Hello, i got this type of error when load image in html using load view laravel
ErrorException
unlink(C:\xampp\tmp/__tcpdf_37d1e4f971c0d0a2731642f7ddec5a4b_imgmask_alpha_cffc8bba4895ae75cc297aede110c0b2): No such file or directory

**Comment by elibyy** [comment]
Hey @manishpanchal,
This seems to be unrelated to the current issue if you could open a new Issue detailing the error
Thanks

**Comment by it-can** [comment]
@manishpanchal I think this is a problem with tcpdf 6.3.2, try installing tcpdf 6.2.26
