### ISSUE TITLE
Sum of table fields on every page.

### ISSUE THREAD

**Issue by riyas1012** [elibyy/tcpdf-laravel#57]
I have total of 14 records and when I print them in tcpdf I'm getting them as two pages as shown below.
Page1
![image1](https://user-images.githubusercontent.com/11472268/42747896-c520ce46-88fb-11e8-834b-b5b8d1840f1a.jpg)
Page2
![image2](https://user-images.githubusercontent.com/11472268/42747909-cf5213a2-88fb-11e8-9a9b-404b1d178503.jpg)

In the 1st image final row is showing 11th record.

But I want it to show my total marks of current page. My expected PDF format is mentioned below.
Expected Page1:
![image3](https://user-images.githubusercontent.com/11472268/42747958-fd468612-88fb-11e8-8149-28bb1e4cb23c.jpg)
Expected Page2:
![image4](https://user-images.githubusercontent.com/11472268/42747972-06021c58-88fc-11e8-8cca-d55cf283b3dd.jpg)

How can I achieve this in tcpdf? or is there any alternative for this to use in laravel?

**Comment by elibyy** [comment]
Hey @riyas1012,
I'm sorry as I'm unsure how you can achieve that, my library is only a wrapper for [TCPDF](https://github.com/tecnickcom/TCPDF) so you should submit an issue there

**Comment by riyas1012** [comment]
Thanks @elibyy
