### ISSUE TITLE
local Image  example ??

### ISSUE THREAD

**Issue by a-moses** [elibyy/tcpdf-laravel#6]
how can i place jpg or png file into pdf and what is the path for the libery in tcpdf config file.

for example Laravel -> storage -> pics

??

```
'image_directory' => '????',
```

**Comment by elibyy** [comment]
you should provide an accessible URL or full file-system path

**Comment by a-moses** [comment]
if my folder (pics) in Laravel  storage folder what i need to write ? like this ? 

``` php
'storage_path('pics')';
```

**Comment by elibyy** [comment]
without the '', look [here ](https://github.com/tecnickcom/TCPDF/search?utf8=%E2%9C%93&q=K_PATH_IMAGES)too for more info

**Comment by a-moses** [comment]
@elibyy  could you give some simple example from local project folder, this is not working.
