### ISSUE TITLE
How to edit existing pdf file

### ISSUE THREAD

**Issue by phanngoctuan1990** [elibyy/tcpdf-laravel#62]
hi,
I trying upload pdf file (already signature) and i want add more signature into pdf file, but when i add new signature then old signature will lost.
so if you have any idea or example please tell me.
many thanks!

**Comment by elibyy** [comment]
Hey,
I'm unsure about signing PDF's so you should check out tcpdf [docs](https://tcpdf.org/examples/example_052/) or [this](https://stackoverflow.com/questions/16100109/tcpdf-adding-digital-signature-to-the-created-pdf)

**Comment by elibyy** [comment]
This issue is being closed due to inactivity
