### ISSUE TITLE
Can't download sample.pdf

### ISSUE THREAD

**Issue by 1101aybs** [elibyy/tcpdf-laravel#63]
I tried your tutorial but then it always says can't download the file.
![untitled](https://user-images.githubusercontent.com/42330954/44011390-e7c61406-9eea-11e8-9013-3d5797f73104.png)

Hope you see this. Thanks !

**Comment by 1101aybs** [comment]
I tried also adding the configuration for LUMEN hoping it would solve the issue but when i refreshed the page it turned into this
![fatal](https://user-images.githubusercontent.com/42330954/44011728-cd9b353c-9eec-11e8-82b0-3d2a9f0402a4.png)

**Comment by elibyy** [comment]
Hey there,
If you could post more information such as laravel/lumen version
PHP version and running is
Sample/reproducible code
And the errors/traces as text as it's unclear by the image you've posted how my library is involved

**Comment by 1101aybs** [comment]
Actually I'm not really sure what is the cause of this. I just tried your tutorial about tcpdf and then when i tried to click the button (see the first picture i sent a while ago) to generate the sample pdf , the pop up notification from the browser showed and said that I can't download the sample.pdf file

**Comment by elibyy** [comment]
Hey there,
I Won't be able to help if you cannot provide some code or some reference to where the error is originating in my code.
So if you could provide some more information such as code used, tutorial link and so on

**Comment by 1101aybs** [comment]
It's okay. Thank you for the time 😊
