### ISSUE TITLE
setHeaderCallback() images missing & header margin

### ISSUE THREAD

**Issue by acirinelli** [elibyy/tcpdf-laravel#68]
This used to work perfectly until I updated to 5.7. Now the image is missing and my margins are not working. The cell is at the top of the page rather than pushed down by the header margin. Any ideas?

config/tcpdf: 'margin_header' => '0.45'
```
$pdf = new PDF();
$pdf::SetMargins(0.5, 1.3, 0.5);

return $pdf::setHeaderCallback(function($pdf) use ($title, $subtitle)
{
    $pdf->Image(\URL::asset('css/img/logos/pdf_header.png'), '', 0.5, '', 0.5, '', '', 'T', false, 300, '', false, false, 0, false, false, false);
    $pdf->SetFont('helvetica', 'B', 14);
    $pdf->Cell(0, 0, $title, 0, false, 'R', false, '', 0, false, 'T', 'M');
    $pdf->Ln();
    $pdf->SetFont('helvetica', 'R', 12);
    $pdf->Cell(0, 0.22, $subtitle, 0, false, 'R', false, '', 0, false, 'T', 'B');
});
```

**Comment by acirinelli** [comment]
@elibyy  I had to include $pdf::SetHeaderMargin(0.45); to get the header margin correct. I guess that's fine, but still no images.
I was able to easily get the images to show up with the default TCPDF header() function: $pdf::SetHeaderData(PDF_HEADER_LOGO, ...)

**Comment by acirinelli** [comment]
Additional info: possibly the missing headers could be related to images just not working because I also have some image tags like: `<img src="url_to_img" />` in the html and they used to work just fine and now they do not show up either.

**Comment by elibyy** [comment]
Hey @acirinelli ,
Sorry for the delay,
A few questions to clarify:

- Why are you invoking `new PDF` you should call methods statically instead.
- if you run `dd(URL::asset('css/img/logos/pdf_header.png'))` is that URL accessible? Please note that the resources diretory was changed on [5.7](https://laravel-news.com/laravel-5-7-resources-directory-changes)
- Configuration are loaded using the service provider, so can you confirm the constant `PDF_MARGIN_HEADER` value?

**Comment by acirinelli** [comment]
@elibyy I will look into calling the methods statically instead, thanks for the heads up.

This is going to sound crazy, but I just happened to run composer update and it looks like tecnickcom/tcpdf was updated from 6.2.22 => 6.2.25, which resolved the issue.

Edit: Slight correction, images that use a URL directly to a file outside of the resources directory are back. Such as avatars & logos stored on S3. Files in URL::assets are still missing.

**Comment by acirinelli** [comment]
@elibyy One more comment on images, just for clarification sake as it may help someone else:
I found this issue that has been resolved https://github.com/tecnickcom/TCPDF/pull/98/commits/cf37343faeb3c6ad1abe44f97016f9f0c3fe35fd
and notice the package is checking the file with file_exists(), however testing file_exists(asset(...)) returns false, while file_exists(public_path(...)) returns true. There is the problem.

**Comment by acirinelli** [comment]
> * Configuration are loaded using the service provider, so can you confirm the constant `PDF_MARGIN_HEADER` value?

dd(PDF_MARGIN_HEADER) spits out the value that I set in the config file. This issue could just be me not understanding how it works. I assumed that these values would default into the PDF without initializing them.

I build a function like so, that I call on all my PDFs now and the margins work fine:
```
public function setMargins()
{
    PDF::SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
    PDF::SetHeaderMargin(PDF_MARGIN_HEADER);
    PDF::SetFooterMargin(PDF_MARGIN_FOOTER);
    PDF::SetAutoPageBreak(true, 0.5);
}
```

**Comment by NanoDev777** [comment]
@acirinelli 
can you tell me how you have configured your tcpdf.php file since I can not configure the margin of my header please

**Comment by acirinelli** [comment]
> @acirinelli
> can you tell me how you have configured your tcpdf.php file since I can not configure the margin of my header please

As described above, you have to use `PDF::SetHeaderMargin(PDF_MARGIN_HEADER)`. This will pull the value from the config file which sets/overrides the default `PDF_MARGIN_HEADER`. These values don't seem to initialize on their own.
