### ISSUE TITLE
Include css using mix

### ISSUE THREAD

**Issue by amrography** [elibyy/tcpdf-laravel#71]
Hi,

First, thanks for the great effort that done. 

I am trying to load $contents from blade view. I am getting the content right in place, but the css stylesheet is not include. I am using laravel mix to generate a one stylesheet (including this in my header)

`<link href="{{ mix('/css/app.css') }}" rel="stylesheet">`

**Comment by elibyy** [comment]
Hey @amrography,
Sorry for the delay, kinda busy at work.
As far as I know, TCPDF doesn't support CSS files but only inline styling is supported [[ref](https://stackoverflow.com/questions/19002634/how-to-use-external-css-in-tcpdf-pdf-generation)]

--
Please let me know if there's anything else I can assist with
Eli
