### ISSUE TITLE
modify header margin

### ISSUE THREAD

**Issue by NanoDev777** [elibyy/tcpdf-laravel#73]
How can I modify the margin of my header? taking into account that the version of my laravel project is 5.5. * and the version of its tcpdf package that I am using is: 5.5.1 it may be easier in new versions of your package, but for reasons of requirements I do not Is it possible to update it, then how can I do this, for my current version?

**Comment by elibyy** [comment]
Check [this](https://stackoverflow.com/questions/5503969/tcpdf-how-to-adjust-height-of-header) out, Hope this helps

**Comment by elibyy** [comment]
This issue is being closed due to inactivity
