### ISSUE TITLE
datauri in writehtml src

### ISSUE THREAD

**Issue by AskinSavascisi** [elibyy/tcpdf-laravel#74]
Hi, does tcpdf support datauri in writehtml src tags?

(i'm using elibyy/tcpdf-laravel)

i don't want to store the signatures from my clients on my server so instead i've tried to store them as datauri's in my db.

example code:
```
$html .='<img src="'.$data_uri.'" width="300">';
PDF::Writehtml($html);
```

i get an empty space where the signature should come.

i can achieve this with PDF::Image('a'.$datauri) however its not responsive to my pdf then..

Thanks in advance

**Comment by elibyy** [comment]
Hey there,
Just to clarify, if you print the HTML to the browser the image is seen?
Also, try and check [this](https://sourceforge.net/p/tcpdf/patches/79/) out.
And last, you should simply write your image to a temp file on the server and provide the full path as src

**Comment by AskinSavascisi** [comment]
Hi, 

Forgot to mention it sorry.  İt doesn't show on the browser. İ want to capture the signature forever on my database just to be safe. İ deliver goods worth €3000, so i let my customers sign for delivery.

**Comment by elibyy** [comment]
Just to confirm, Your data uri starts with `data:image/gif;base64,`?

**Comment by AskinSavascisi** [comment]
Yes, when i manually pasted it on the browser my db value,  it successfully shows the image.

**Comment by elibyy** [comment]
can you provide an actual output of the html?
