### ISSUE TITLE
How to download pdf output from a post request?

### ISSUE THREAD

**Issue by lukio3** [elibyy/tcpdf-laravel#77]
Hey @elibyy 

The use case I am trying to resolve, in simple terms is:

1. Grab some html from a page
2. Submit it via ajax to a controller
3. Output to pdf 

My approach has been to use:

```
$string = PDF::Output( 'sometitle.pdf', 'S' );
```
and then 
```
    return response()->streamDownload(function () use ($string) {
        echo $string;
      }, 'sometitle.pdf, [
        "Content-type" => "application/pdf",
        "Content-Disposition:attachment"
      ]);
```
which does return a result in the browser, but not an actual file download, just a string representation of the file. Without then, going down a rabbit hole of trying to stream that string in .js do you know how I could be handling this?

As always, much appreciated, 

Luke

**Comment by elibyy** [comment]
Hey Luke,
As far as I'm aware you cannot download a file using JS, therefore you should use a fake form or something alike to submit the data to the server and then just use the 'D' option in the output method.

Some reference:
https://stackoverflow.com/q/4545311
https://stackoverflow.com/a/42815974

Hope this helps,
Eli

**Comment by lukio3** [comment]
Hi Eli,

I appreciate your response thanks.

Yes it seems there are a range of 3rd party js libraries to handle this type of thing but for simplicities sake i am going to descope this use-case from my app.

Thanks,

Luke
