### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by andreacris** [elibyy/tcpdf-laravel#85]
Hi,

I tried to add a font with this code:
```php
$pdf = new PDF;
$nunito_regular = $pdf::addTTFfont('uploads/fonts/Nunito-Regular.ttf', 'TrueTypeUnicode', '', 96);
```
but I receive this error:
the method addTTFfont does not exists in TCPDF

**Comment by elibyy** [comment]
Hey there,
so A. It is unclear why are you doing new when it should be provided from the facade.
And b. It would help if you provide some more information of the error, it can be censored as much as needed but trace and such would help

**Comment by it-can** [comment]
try this:


```
$pdf = new PDF;
$nunito_regular = $pdf->addTTFfont('uploads/fonts/Nunito-Regular.ttf', 'TrueTypeUnicode', '', 96);
```

**Comment by andreacris** [comment]
> 
> 
> Hey there,
> so A. It is unclear why are you doing new when it should be provided from the facade.
> And b. It would help if you provide some more information of the error, it can be censored as much as needed but trace and such would help

A. I made it wrong.
B. If I try adding a font as follow: 
```
namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use PDF;
public function getTCPDF()
{
      PDF::addTTFfont('uploads/fonts/Nunito-Bold.ttf', 'TrueTypeUnicode', '', 96);
}
```
I get this runtime exception:

the method addTTFfont does not exists in TCPDF

```
public function __call($method, $args)
{
        if (method_exists($this->tcpdf, $method)) {
            return call_user_func_array([$this->tcpdf, $method], $args);
        }
        throw new \RuntimeException(sprintf('the method %s does not exists in TCPDF', $method));
}
```

**Comment by it-can** [comment]
@andreacris ```addTTFfont``` is a function in the ```TCPDF_FONTS``` class... in ```tcpdf_fonts.php```

in tcpdf take a look at these functions:

```
AddFont()
SetFont()
```

**Comment by andreacris** [comment]
I solved doing this:
1) convert the font on http://fonts.snm-portal.com/
2) download and put files in /vendor/tecnickcom/tcpdf/fonts
3) set the new font with PDF::setFont('newfont','', 14);

**Comment by withmussy** [comment]
tnx @andreacris it was a really easy way

**Comment by gilbertdim** [comment]
Try this solution. I use the tcpdf_addfont.php script to add a font in TCPDF.

https://stackoverflow.com/questions/34990003/custom-font-installation-in-laravel-tcpdf/65246388#65246388
