### ISSUE TITLE
Call to undefined method Elibyy\TCPDF\Facades\TCPDF::write()

### ISSUE THREAD

**Issue by tgbv** [elibyy/tcpdf-laravel#87]
I have installed the project as suggested via `composer`, then appended the class to the service and set up class alias. Though at this simple code it fails with the given error.
```
$T = new \PDF("L", 'A3');
$T->write('test');
return $T->output(__DIR__ .'/statistics.pdf', 'F');
```

> Call to undefined method Elibyy\TCPDF\Facades\TCPDF::write()

I use Laravel 6. How can I solve this problem?

**Comment by elibyy** [comment]
Hey there,
I'm not sure if this is still relevant but you are using the API wrong,
please refer to the README to understand how to integrate this library
