### ISSUE TITLE
The images are not displaying in RTL mode

### ISSUE THREAD

**Issue by adam1920** [elibyy/tcpdf-laravel#89]
If `$pdf->setRTL(true);`
next image isn't displaying
`<img src="https://hishtalmut2020.kranoth.org.il/assets/images/logo.png?ver=20191229" alt="" width="337" height="48">`

But it is displaying if `$pdf->setRTL(false);`

**Comment by elibyy** [comment]
Hey there,
Sorry for the delay, this seems to be TCPDF issue and not library related.
Unsure how I can help any further
