### ISSUE TITLE
Header and footer fails to render

### ISSUE THREAD

**Issue by tsalufe** [elibyy/tcpdf-laravel#9]
Not sure why. TCPdf fails to render header and footer. But TCPDF(original tecknicom/TCPDF) is fine. I have to switch to TCPDF for my PdfWriter.

**Comment by a-moses** [comment]
have you try this :

https://github.com/elibyy/tcpdf-laravel/blob/master/README.md#headerfooter-helpers

**Comment by tsalufe** [comment]
Is there a reason why TCPdf->SetHeaderData didn't succeed? I assume TCPdf calls TCPdfHelper which is a child class of TCPDF, right?

**Comment by elibyy** [comment]
this was modified to allow users to customize the header/footer easily

**Comment by tsalufe** [comment]
So I have to do like this?
`PDF::setHeaderCallback(function($tcpdf) {
       $tcpdf->SetHeaderData('path_to_logo', 40, 'my header title', 'my header author string');
});
PDF::Header();
`

**Comment by tsalufe** [comment]
I mean, it doesn't look easier to use unless the implementation should be different.

**Comment by elibyy** [comment]
most of the people just create their own header/footer directly in their HTML, so this should be for HTML rendering

**Comment by tsalufe** [comment]
OK. I'm not using HTML because I need to plot graphs inside pdf. Thanks anyway.

**Comment by a-moses** [comment]
So @tsalufe  you can create  blank html code with only header and footer.
