### ISSUE TITLE
printing Pashto Language 

### ISSUE THREAD

**Issue by fidamuhammadkhan** [elibyy/tcpdf-laravel#91]
when i am trying to print Pashto (فدامحمد) Language character its print ???? i also set the encoding to utf-8 in config/tcpdf.php file but its not working

**Comment by fidamuhammadkhan** [comment]
` $html_content = '<h1>Generate a PDF using TCPDF in laravel </h1>
    <h4>HI<br/>سلامونه مینه والو ټیسټنګ</h4>';
    PDF::SetTitle('Sample PDF');
    PDF::AddPage();
    PDF::writeHTML($html_content);
    PDF::Output('SamplePDF.pdf');
    }`


Output is :
![Capture](https://user-images.githubusercontent.com/45406901/81010189-19940f80-8e6b-11ea-8f8a-c02e31b6b599.JPG)

**Comment by elibyy** [comment]
Hey there,
As far as i know, you should use a font that supports your language as well
Please check [this sample](https://tcpdf.org/examples/example_018/)
