### ISSUE TITLE
Encoding UTF-8 Problem

### ISSUE THREAD

**Issue by dsanthoshraj** [elibyy/tcpdf-laravel#93]
Pdf working only in english language. Not working in Thai language kindly. Give me a solution for this issue. 

![image](https://user-images.githubusercontent.com/36885729/87158347-3a4e6a80-c2dd-11ea-9fc4-97eae51f034f.png)

**Comment by elibyy** [comment]
Hey there,
I think you should use a custom font that supports Thai Maybe this [link](https://www.programmerthailand.com/tutorial/post/view/217/%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%9F%E0%B8%AD%E0%B8%99%E0%B8%97%E0%B9%8C%E0%B8%88%E0%B8%B2%E0%B8%81-tcpdf-%E0%B8%88%E0%B8%B2%E0%B8%81-tcpdf-addfont.php) could help
or this [one](https://tcpdf.org/docs/fonts/)
