### ISSUE TITLE
Image in blade not working

### ISSUE THREAD

**Issue by eli-cquoin** [elibyy/tcpdf-laravel#95]
I separated the header into a blade file. All are working except for the logo. I checked the image and the path is correct. I even converted it from png to jpg because I read that it's a common issue.

    @php
      $logo_url = asset("storage/uploads/celeb_logo.jpg")
    @endphp
    <table>
        <thead>
            <tr>
                <th width="120"><img src="{{ $logo_url }}" width="120" height="auto"/></th>

What's wrong with how I call the image?

**Comment by elibyy** [comment]
Hey there,
Not sure if that's the error but I think it has to do with `height="auto"`

**Comment by eli-cquoin** [comment]
Hi,
Thanks for your reply. I was able to make it work by not using the `asset(url)`. Instead, I used the direct url ` <th width="120"><img src="storage/uploads/celeb_logo.jpg" alt="test alt attribute" width="120" height="80" border="0" /></th>`. Although, it would be more 'pretty' if I could use it.

**Comment by eli-cquoin** [comment]
Hi again,
I noticed that the image is not working when I moved my code from controller to listener (because the process needs to be queued to work). Any other suggestions? Thanks!

**Comment by elibyy** [comment]
Try using `storage_path()` for the file
