### ISSUE TITLE
$pdfa_mode issue

### ISSUE THREAD

**Issue by eli-cquoin** [elibyy/tcpdf-laravel#96]
I'm making some changes in my code where I want to save the path and the path name each time I create a PDF. However, when I run the code through `queue:work`, I always get this:
`ErrorException: Undefined property: Elibyy\TCPDF\TCPDFHelper::$pdfa_mode in /Applications/Work/celeb/vendor/tecnickcom/tcpdf/tcpdf.php:10897`

Then I reverted my code to when it was working, but I still get the same error.

**Comment by elibyy** [comment]
You should use `PDF::reset` at the end of your loop as specified in the readme
![image](https://user-images.githubusercontent.com/836551/89281587-fa1ba700-d652-11ea-8d82-a89dd481d2f6.png)

Please let me know if it works
