### ISSUE TITLE
Special character like Ñ not being printed.

### ISSUE THREAD

**Issue by eli-cquoin** [elibyy/tcpdf-laravel#98]
Hello,

I have names need to be printed which includes special characters like `Ñ`.
But when it gets printed, it gets replaced with dash.
Is it related to my DB collation (utf8mb4_unicode_ci)?
![Screen Shot 2020-08-16 at 10 34 26 AM](https://user-images.githubusercontent.com/65450832/90325234-9fb40c00-dfab-11ea-9b62-800f04ede88a.png)

**Comment by elibyy** [comment]
Hey,
This seems like TCPDF problem, maybe this will help you
https://stackoverflow.com/questions/17680783/how-to-display-html-ohm-special-character-in-tcpdf
